name = "catppuccin-latte"

[colors]
bg = "#eff1f5"
fg = "#4c4f69"
text_correct = "#40a02b"
text_incorrect = "#d20f39"
text_incorrect_bg = "#f5c2cf"
text_pending = "#9ca0b0"
text_cursor_bg = "#dc8a78"
text_cursor_fg = "#eff1f5"
focused_key = "#df8e1d"
accent = "#1e66f5"
accent_dim = "#ccd0da"
border = "#ccd0da"
border_focused = "#1e66f5"
header_bg = "#e6e9ef"
header_fg = "#4c4f69"
bar_filled = "#1e66f5"
bar_empty = "#e6e9ef"
error = "#d20f39"
warning = "#df8e1d"
success = "#40a02b"
