name = "catppuccin-mocha"

[colors]
bg = "#1e1e2e"
fg = "#cdd6f4"
text_correct = "#a6e3a1"
text_incorrect = "#f38ba8"
text_incorrect_bg = "#45273a"
text_pending = "#a6adc8"
text_cursor_bg = "#f5e0dc"
text_cursor_fg = "#1e1e2e"
focused_key = "#f9e2af"
accent = "#89b4fa"
accent_dim = "#45475a"
border = "#45475a"
border_focused = "#89b4fa"
header_bg = "#313244"
header_fg = "#cdd6f4"
bar_filled = "#89b4fa"
bar_empty = "#313244"
error = "#f38ba8"
warning = "#f9e2af"
success = "#a6e3a1"
