name = "dracula"

[colors]
bg = "#282a36"
fg = "#f8f8f2"
text_correct = "#50fa7b"
text_incorrect = "#ff5555"
text_incorrect_bg = "#44242a"
text_pending = "#9aadce"
text_cursor_bg = "#f1fa8c"
text_cursor_fg = "#282a36"
focused_key = "#f1fa8c"
accent = "#bd93f9"
accent_dim = "#44475a"
border = "#44475a"
border_focused = "#bd93f9"
header_bg = "#44475a"
header_fg = "#f8f8f2"
bar_filled = "#bd93f9"
bar_empty = "#44475a"
error = "#ff5555"
warning = "#f1fa8c"
success = "#50fa7b"
