name = "farout"

[colors]
bg = "#0f0908"
fg = "#E0CCAE"
text_correct = "#a4896f"
text_incorrect = "#bf472c"
text_incorrect_bg = "#392D2B"
text_pending = "#A67458"
text_cursor_bg = "#0f0908"
text_cursor_fg = "#f2a766"
focused_key = "#f2a766"
accent = "#d47d49"
accent_dim = "#392D2B"
border = "#392D2B"
border_focused = "#d47d49"
header_bg = "#392D2B"
header_fg = "#E0CCAE"
bar_filled = "#a67458"
bar_empty = "#392D2B"
error = "#bf472c"
warning = "#f2a766"
success = "#a4896f"
