name = "kanagawa-wave"

[colors]
bg = "#1f1f28"
fg = "#dcd7ba"
text_correct = "#76946a"
text_incorrect = "#c34043"
text_incorrect_bg = "#43242B"
text_pending = "#727169"
text_cursor_bg = "#2d4f67"
text_cursor_fg = "#c8c093"
focused_key = "#c0a36e"
accent = "#7e9cd8"
accent_dim = "#2A2A37"
border = "#54546D"
border_focused = "#7e9cd8"
header_bg = "#2A2A37"
header_fg = "#dcd7ba"
bar_filled = "#7e9cd8"
bar_empty = "#2A2A37"
error = "#c34043"
warning = "#c0a36e"
success = "#76946a"
