name = "kanagawa-lotus"

[colors]
bg = "#f2ecbc"
fg = "#545464"
text_correct = "#6f894e"
text_incorrect = "#c84053"
text_incorrect_bg = "#d9a594"
text_pending = "#8a8980"
text_cursor_bg = "#5d57a3"
text_cursor_fg = "#f2ecbc"
focused_key = "#77713f"
accent = "#4d699b"
accent_dim = "#e7dba0"
border = "#a5a37d"
border_focused = "#4d699b"
header_bg = "#e7dba0"
header_fg = "#545464"
bar_filled = "#597b75"
bar_empty = "#d9d0a3"
error = "#c84053"
warning = "#77713f"
success = "#6f894e"
