name = "terminal-default"

[colors]
bg = "reset"
fg = "reset"
text_correct = "green"
text_incorrect = "red"
text_incorrect_bg = "reset"
text_pending = "darkgray"
text_cursor_bg = "reset"
text_cursor_fg = "reset"
focused_key = "yellow"
accent = "blue"
accent_dim = "darkgray"
border = "darkgray"
border_focused = "blue"
header_bg = "reset"
header_fg = "reset"
bar_filled = "blue"
bar_empty = "darkgray"
error = "red"
warning = "yellow"
success = "green"
